name: Node.js CI

on:
  push:
    branches:
      - master
      - client_master
      - dev
    paths-ignore:
      - "Crawler_PhongTro123/**"

  pull_request:
    branches:
      - master
      - client_master
      - dev
    paths-ignore:
      - "Crawler_PhongTro123/**"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: /home/runner/work/DoAnTimPhongTro_QLQTPM/DoAnTimPhongTro_QLQTPM/server
      - run: npm run-script build
        working-directory: /home/runner/work/DoAnTimPhongTro_QLQTPM/DoAnTimPhongTro_QLQTPM/server
      - run: npm ci
        working-directory: /home/runner/work/DoAnTimPhongTro_QLQTPM/DoAnTimPhongTro_QLQTPM/client
      - run: npm run-script build
        working-directory: /home/runner/work/DoAnTimPhongTro_QLQTPM/DoAnTimPhongTro_QLQTPM/client
